### ISSUE TITLE
Where to get vq-gan-f8-mix-840.pt

### ISSUE THREAD

**Issue by Night1099** [giuvecchio/matfuse-sd#6]
can not find where to download vq-gan-f8-mix-840.pt as required in matfuse-ldm-vq_f8.yaml and it doesnt auto download

another problem i have is I cant resume a training from checkpoint for autoencoder i get this error

```
Restoring states from the checkpoint file at /workspace/matfuse-sd/logs/2024-06-06T22-56-55_multi-vq_f8/checkpoints/last.ckpt
/root/anaconda3/envs/sdiff/lib/python3.10/site-packages/pytorch_lightning/core/datamodule.py:423: LightningDeprecationWarning: DataModule.setup has already been called, so it will not be called again. In v1.6 this behavior will change to always call DataModule.setup.
  rank_zero_deprecation(
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
lr_d 3.6e-05
lr_g 3.6e-05
Traceback (most recent call last):
  File "/workspace/matfuse-sd/src/main.py", line 904, in <module>
    trainer.fit(model, data)
  File "/root/anaconda3/envs/sdiff/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 553, in fit
    self._run(model)
  File "/root/anaconda3/envs/sdiff/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 918, in _run
    self._dispatch()
  File "/root/anaconda3/envs/sdiff/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 986, in _dispatch
    self.accelerator.start_training(self)
  File "/root/anaconda3/envs/sdiff/lib/python3.10/site-packages/pytorch_lightning/accelerators/accelerator.py", line 92, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/root/anaconda3/envs/sdiff/lib/python3.10/site-packages/pytorch_lightning/plugins/training_type/ddp_spawn.py", line 158, in start_training
    mp.spawn(self.new_process, **self.mp_spawn_kwargs)
  File "/root/anaconda3/envs/sdiff/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/root/anaconda3/envs/sdiff/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 189, in start_processes
    process.start()
  File "/root/anaconda3/envs/sdiff/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/root/anaconda3/envs/sdiff/lib/python3.10/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
  File "/root/anaconda3/envs/sdiff/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/root/anaconda3/envs/sdiff/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/root/anaconda3/envs/sdiff/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 58, in _launch
    self.pid = util.spawnv_passfds(spawn.get_executable(),
  File "/root/anaconda3/envs/sdiff/lib/python3.10/multiprocessing/util.py", line 452, in spawnv_passfds
    return _posixsubprocess.fork_exec(
ValueError: bad value(s) in fds_to_keep
```

Thanks

**Comment by giuvecchio** [comment]
Hi, thanks for pointing out the issue. The `ckpt_path` in `matfuse-ldm-vq_f8.yaml` should be replaced with the path your local autoencoder weights. We will update the readme to make it clear.
Trained weights should be available later this week or early next week.

**Comment by Night1099** [comment]
> Hi, thanks for pointing out the issue. The `ckpt_path` in `matfuse-ldm-vq_f8.yaml` should be replaced with the path your local autoencoder weights. We will update the readme to make it clear. Trained weights should be available later this week or early next week.

Ok i did figure that was the case but get this error when using vgg.pth or the epoch=000000.ckpt made by autoencoder training

```
Traceback (most recent call last):
  File "/workspace/matfuse-sd/src/main.py", line 697, in <module>
    model = instantiate_from_config(config.model).to(device)
  File "/workspace/matfuse-sd/src/ldm/util.py", line 119, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/workspace/matfuse-sd/src/ldm/models/diffusion/ddpm.py", line 678, in __init__
    self.instantiate_first_stage(first_stage_config)
  File "/workspace/matfuse-sd/src/ldm/models/diffusion/ddpm.py", line 749, in instantiate_first_stage
    model = instantiate_from_config(config)
  File "/workspace/matfuse-sd/src/ldm/util.py", line 119, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/workspace/matfuse-sd/src/ldm/models/autoencoder.py", line 393, in __init__
    self.init_from_ckpt(ckpt_path, ignore_keys=[])
  File "/workspace/matfuse-sd/src/ldm/models/autoencoder.py", line 396, in init_from_ckpt
    sd = torch.load(path, map_location="cpu")["vqmodel"]
KeyError: 'vqmodel'
```

I guess i dont know where 

"path your local autoencoder weights"

is

**Comment by Night1099** [comment]
I have found more info moving to new issue with more errors
